### PR TITLE
feat: Nancydeng/database change to typescript and move to logger, loggingmodel

### PR DESCRIPTION
**Pull request by nanyi-deng**

### CODE REVIEW

**Comment by nanyi-deng** [comment]
description: 
1. change from db folder to controller and model file
2. convert js to ts.

**Comment by aidanprior** [comment]
@nanyi-deng can you change target to `dev` please?

**Comment by nanyi-deng** [comment]
just did @aidanprior , sorry about that!

**Review by AchillesHeir — APPROVED** [review]
Looks good to me - Kenny

**Pull request merged**
